

#ifdef __DJGPP__


BEGIN_GFX_DRIVER_LIST
    //
    GFX_DRIVER_VESA3
    GFX_DRIVER_VESA2L
    GFX_DRIVER_VESA1
    GFX_DRIVER_VGA
    GFX_DRIVER_MODEX
    //
END_GFX_DRIVER_LIST


BEGIN_COLOR_DEPTH_LIST
    //
    COLOR_DEPTH_8
    //
END_COLOR_DEPTH_LIST


BEGIN_DIGI_DRIVER_LIST
    //
    DIGI_DRIVER_SOUNDSCAPE
    DIGI_DRIVER_AUDIODRIVE
    DIGI_DRIVER_WINSOUNDSYS
    DIGI_DRIVER_SB
    //
END_DIGI_DRIVER_LIST


BEGIN_MIDI_DRIVER_LIST
    //
END_MIDI_DRIVER_LIST


BEGIN_JOYSTICK_DRIVER_LIST
    //
    JOYSTICK_DRIVER_SIDEWINDER
    JOYSTICK_DRIVER_GAMEPAD_PRO
    JOYSTICK_DRIVER_GRIP
    JOYSTICK_DRIVER_STANDARD
    JOYSTICK_DRIVER_SNESPAD
    JOYSTICK_DRIVER_PSXPAD
    JOYSTICK_DRIVER_N64PAD
    //
END_JOYSTICK_DRIVER_LIST


#endif /* __DJGPP__ */
