/* include/datafile.h
 * 
 *  Converted datafile header for support/fakenes.dat .
 *  See data.c for definitions.
 *  Do not hand edit.
 */

#ifndef ALLEGRO_H
#error You must include allegro.h
#endif

#ifndef INCLUDE_DATAFILE_H
#define INCLUDE_DATAFILE_H

#ifdef __cplusplus
extern "C" {
#endif



extern DATAFILE datafile_data[];

#define DATAFILE_DEFAULT_PALETTE 0
#define DATAFILE_EGA_PALETTE_1 1
#define DATAFILE_EGA_PALETTE_2 2
#define DATAFILE_GNUBOY_PALETTE 3
#define DATAFILE_GRAYSCALE_PALETTE 4
#define DATAFILE_GUI_CLASSIC_THEME_MOUSE_SPRITE 5
#define DATAFILE_GUI_CLASSIC_THEME_PALETTE 6
#define DATAFILE_GUI_GENERIC_THEME_MOUSE_SPRITE 7
#define DATAFILE_GUI_GENERIC_THEME_PALETTE 8
#define DATAFILE_GUI_PANTA_THEME_BACKGROUND_IMAGE 9
#define DATAFILE_GUI_PANTA_THEME_MOUSE_SPRITE 10
#define DATAFILE_GUI_PANTA_THEME_PALETTE 11
#define DATAFILE_GUI_STAINLESS_STEEL_THEME_BACKGROUND_IMAGE 12
#define DATAFILE_GUI_STAINLESS_STEEL_THEME_MOUSE_SPRITE 13
#define DATAFILE_GUI_STAINLESS_STEEL_THEME_PALETTE 14
#define DATAFILE_GUI_ZERO_4_THEME_BACKGROUND_IMAGE 15
#define DATAFILE_GUI_ZERO_4_THEME_MOUSE_SPRITE 16
#define DATAFILE_GUI_ZERO_4_THEME_PALETTE 17
#define DATAFILE_GUN_SPRITE 18
#define DATAFILE_LARGE_FONT 19
#define DATAFILE_MODERN_NTSC_PALETTE 20
#define DATAFILE_MODERN_PAL_PALETTE 21
#define DATAFILE_NESTER_PALETTE 22
#define DATAFILE_NESTICLE_PALETTE 23
#define DATAFILE_SMALL_FONT 24
#define DATAFILE_SMALL_FONT_CLEAN 25
#define DATAFILE_COUNT 26



#ifdef __cplusplus
}
#endif

#endif /* include guard */

/* end of include/datafile.h */



